### ISSUE TITLE
Adding Form Validation

### ISSUE THREAD

**Issue by OrPerl** [aburd/beats-with-friends#17]
## Feature Request

**Is your feature request related to a problem? Please describe.**
To improve the development experience, instead of implementing form validation manually, it is more effective to have a dedicated form validation library that can help manage both validations, error messages, and easiness of retrieving form values. 

**Describe the solution you'd like**
[Felte for Solid](https://felte.dev/docs/solid/getting-started) is a recent entry for Solid for form validations.
It has good documentation, and functionality, and is stable for usage.
Additionally [Hope-UI](https://hope-ui.com/) has built-in [support](https://hope-ui.com/docs/data-entry/form-control) for it.

**Describe alternatives you've considered**
Unfortunately, form validation for Solid is still quite barebone.
The other alternative for felte is [Solar Forms](https://github.com/kajetansw/solar-forms).
While I am quite fond of how it is implemented, it is still in early development and cannot be quite trusted for production-grade development.

**Teachability, Documentation, Adoption, Migration Strategy**
Following my [proposal](https://github.com/aburd/beats-with-friends/issues/15) to use [Hope-UI](https://hope-ui.com/), I would recommend referring to both the Felte [documentation](https://felte.dev/docs/solid/getting-started) and Hope-UI's [documentation](https://hope-ui.com/docs/data-entry/form-control) on how to use Felte for the time being.

**Comment by aburd** [comment]
Agreed that there aren't many alternatives, but let's just use what's out there!
